version: 2

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: 6:00
      timezone: Europe/Kiev #Kyiv
    open-pull-requests-limit: 10
    assignees:
      - "mykelangelo"